# Generated by Django 4.2.2 on 2023-07-05 19:28

from django.db import migrations, models
import recepies.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0002_alter_recipeingridient_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingridient',
            name='quantity_as_float',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingridient',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recipeingridient',
            name='unit',
            field=models.CharField(max_length=50, validators=[recepies.validators.validate_unit_of_measure]),
        ),
    ]
