# Generated by Django 4.2.2 on 2023-07-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0005_recipeingredientimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientimage',
            name='image',
            field=models.ImageField(upload_to='recipes/'),
        ),
    ]
