# Generated by Django 4.2.2 on 2023-07-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0007_alter_recipeingredientimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredientimage',
            name='extracted',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
