# Generated by Django 4.2.2 on 2023-07-28 07:23

from django.db import migrations, models
import recepies.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0008_recipeingredientimage_extracted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[recepies.validators.validate_unit_of_measure]),
        ),
    ]
