name: CI/CD Django, Postgres, DigitalOcean

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres_main:
        image: postgres:12
        env:
          POSTGRES_USER: default
          POSTGRES_PASSWORD: default
          POSTGRES_DB: djtesting
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        DEBUG: "0"
        DJANGO_SECREY_KEY: CI_CD_DJANGO_TEST_KEY
        POSTGRES_USER: default
        POSTGRES_PASSWORD: default
        POSTGRES_DB: djtesting
        POSTGRES_PORT: 5432
      run: |
        python manage.py test